version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0861
      POSTGRES_DB: juweria
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: ./server
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: 0861
      PGDATABASE: juweria
      JWT_SECRET: dev-secret
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
      - rabbitmq

volumes:
  pgdata:


